name: Windows Qt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  project: 'terrafirma'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        name: [windows-6.4]
        include:
          - name: windows-6.4
            os: windows-2022
            qt: '6.4.3'
            msvc_toolset: '14.29'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: ${{ matrix.msvc_toolset }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        target: 'desktop'
        cache: 'true'
        cache-key-prefix: ${{ runner.os }}-QtCache-${{ matrix.qt }}

    - name: Create BUILD folder
      run: |
        mkdir ../build
        mkdir ../deploy

    - name: Configure cmake
      working-directory: ../build
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: cmake ${{ github.workspace }} -G "NMake Makefiles"

    - name: Build (Windows)
      working-directory: ../build
      shell: cmd
      run: nmake

    - name: Deploy Qt (Windows)
      working-directory: ../build
      shell: cmd
      run: |
        cp ..\build\${{ env.project }}.exe ..\deploy\${{ env.project }}.exe
        windeployqt ..\deploy

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/deploy/*

