name: Ubuntu Qt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  project: 'terrafirma'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-24.04]
        include:
          - name: ubuntu-24.04
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install qt6-base-dev qt6-base-dev-tools -y

    - name: Create BUILD folder
      run: |
        mkdir ../build

    - name: Configure cmake
      working-directory: ../build
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: cmake ${{ github.workspace }}

    - name: Build (Ubuntu)
      working-directory: ../build
      run: make

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/build/src/${{ env.project }}
